window.Modernizr=function(e,c,l){function o(b,a){return typeof b===a}function x(b,a){for(var h in b)if(m[b[h]]!==l)return a=="pfx"?b[h]:!0;return!1}function k(b,a,h){var c=b.charAt(0).toUpperCase()+b.substr(1),d=(b+" "+v.join(c+" ")+c).split(" ");if(o(a,"string")||o(a,"undefined"))a=x(d,a);else{d=(b+" "+j.join(c+" ")+c).split(" ");a:{var b=d,e;for(e in b)if(c=a[b[e]],c!==l){a=h===!1?b[e]:o(c,"function")?c.bind(h||a):c;break a}a=!1}}return a}function z(){f.input=function(b){for(var a=0,h=b.length;a<
h;a++)y[b[a]]=b[a]in g;return y.list&&(y.list=!!c.createElement("datalist")&&!!e.HTMLDataListElement),y}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));f.inputtypes=function(b){for(var a=0,h,d,e,j=b.length;a<j;a++)g.setAttribute("type",d=b[a]),h=g.type!=="text",h&&(g.value=r,g.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(d)&&g.style.WebkitAppearance!==l?(t.appendChild(g),e=c.defaultView,h=e.getComputedStyle&&e.getComputedStyle(g,
null).WebkitAppearance!=="textfield"&&g.offsetHeight!==0,t.removeChild(g)):/^(search|tel)$/.test(d)||(/^(url|email)$/.test(d)?h=g.checkValidity&&g.checkValidity()===!1:/^color$/.test(d)?(t.appendChild(g),h=g.value!=r,t.removeChild(g)):h=g.value!=r)),G[b[a]]=!!h;return G}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var f={},t=c.documentElement,d=c.createElement("modernizr"),m=d.style,g=c.createElement("input"),r=":)",w={}.toString,u=" -webkit- -moz- -o- -ms- ".split(" "),
v="Webkit Moz O ms".split(" "),j="webkit moz o ms".split(" "),d={},G={},y={},A=[],B=A.slice,C,D=function(b,a,h,d){var e,j,f,i=c.createElement("div"),s=c.body,n=s?s:c.createElement("body");if(parseInt(h,10))for(;h--;)f=c.createElement("div"),f.id=d?d[h]:"modernizr"+(h+1),i.appendChild(f);return e=["&#173;<style>",b,"</style>"].join(""),i.id="modernizr",(s?i:n).innerHTML+=e,n.appendChild(i),s||(n.style.background="",t.appendChild(n)),j=a(i,b),s?i.parentNode.removeChild(i):n.parentNode.removeChild(n),
!!j},E=function(){var b={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(a,h){h=h||c.createElement(b[a]||"div");a="on"+a;var d=a in h;return d||(h.setAttribute||(h=c.createElement("div")),h.setAttribute&&h.removeAttribute&&(h.setAttribute(a,""),d=o(h[a],"function"),o(h[a],"undefined")||(h[a]=l),h.removeAttribute(a))),d}}(),p={}.hasOwnProperty,q;!o(p,"undefined")&&!o(p.call,"undefined")?q=function(b,a){return p.call(b,a)}:q=function(b,a){return a in
b&&o(b.constructor.prototype[a],"undefined")};Function.prototype.bind||(Function.prototype.bind=function(b){var a=this;if(typeof a!="function")throw new TypeError;var h=B.call(arguments,1),c=function(){if(this instanceof c){var d=function(){};d.prototype=a.prototype;var d=new d,e=a.apply(d,h.concat(B.call(arguments)));return Object(e)===e?e:d}return a.apply(b,h.concat(B.call(arguments)))};return c});(function(b,a){var h=b.join(""),d=a.length;D(h,function(a,b){for(var h=c.styleSheets[c.styleSheets.length-
1],h=h?h.cssRules&&h.cssRules[0]?h.cssRules[0].cssText:h.cssText||"":"",j=a.childNodes,s={};d--;)s[j[d].id]=j[d];f.touch="ontouchstart"in e||e.DocumentTouch&&c instanceof DocumentTouch||(s.touch&&s.touch.offsetTop)===9;f.csstransforms3d=(s.csstransforms3d&&s.csstransforms3d.offsetLeft)===9&&s.csstransforms3d.offsetHeight===3;f.generatedcontent=(s.generatedcontent&&s.generatedcontent.offsetHeight)>=1;f.fontface=/src/i.test(h)&&h.indexOf(b.split(" ")[0])===0},d,a)})(['@font-face {font-family:"font";src:url("https://")}',
["@media (",u.join("touch-enabled),("),"modernizr){#touch{top:9px;position:absolute}}"].join(""),["@media (",u.join("transform-3d),("),"modernizr){#csstransforms3d{left:9px;position:absolute;height:3px;}}"].join(""),['#generatedcontent:after{content:"',r,'";visibility:hidden}'].join("")],["fontface","touch","csstransforms3d","generatedcontent"]);d.flexbox=function(){return k("flexOrder")};d["flexbox-legacy"]=function(){return k("boxDirection")};d.canvas=function(){var b=c.createElement("canvas");
return!!b.getContext&&!!b.getContext("2d")};d.canvastext=function(){return!!f.canvas&&!!o(c.createElement("canvas").getContext("2d").fillText,"function")};d.webgl=function(){try{var b=c.createElement("canvas"),a;a=!(!e.WebGLRenderingContext||!b.getContext("experimental-webgl")&&!b.getContext("webgl"))}catch(h){a=!1}return a};d.touch=function(){return f.touch};d.geolocation=function(){return!!navigator.geolocation};d.postmessage=function(){return!!e.postMessage};d.websqldatabase=function(){return!!e.openDatabase};
d.indexedDB=function(){return!!k("indexedDB",e)};d.hashchange=function(){return E("hashchange",e)&&(c.documentMode===l||c.documentMode>7)};d.history=function(){return!!e.history&&!!history.pushState};d.draganddrop=function(){var b=c.createElement("div");return"draggable"in b||"ondragstart"in b&&"ondrop"in b};d.websockets=function(){for(var b=-1,a=v.length;++b<a;)if(e[v[b]+"WebSocket"])return!0;return"WebSocket"in e};d.rgba=function(){m.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+
m.backgroundColor).indexOf("rgba")};d.hsla=function(){m.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+m.backgroundColor).indexOf("rgba")||!!~(""+m.backgroundColor).indexOf("hsla")};d.multiplebgs=function(){m.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(m.background)};d.backgroundsize=function(){return k("backgroundSize")};d.borderimage=function(){return k("borderImage")};d.borderradius=function(){return k("borderRadius")};d.boxshadow=
function(){return k("boxShadow")};d.textshadow=function(){return c.createElement("div").style.textShadow===""};d.opacity=function(){var b=u.join("opacity:.55;")+"";m.cssText=b;return/^0.55$/.test(m.opacity)};d.cssanimations=function(){return k("animationName")};d.csscolumns=function(){return k("columnCount")};d.cssgradients=function(){var b=("background-image:"+"-webkit- ".split(" ").join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+u.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,
-17);m.cssText=b;return!!~(""+m.backgroundImage).indexOf("gradient")};d.cssreflections=function(){return k("boxReflect")};d.csstransforms=function(){return!!k("transform")};d.csstransforms3d=function(){var b=!!k("perspective");return b&&"webkitPerspective"in t.style&&(b=f.csstransforms3d),b};d.csstransitions=function(){return k("transition")};d.fontface=function(){return f.fontface};d.generatedcontent=function(){return f.generatedcontent};d.video=function(){var b=c.createElement("video"),a=!1;try{if(a=
!!b.canPlayType)a=new Boolean(a),a.ogg=b.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),a.h264=b.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),a.webm=b.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(h){}return a};d.audio=function(){var b=c.createElement("audio"),a=!1;try{if(a=!!b.canPlayType)a=new Boolean(a),a.ogg=b.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),a.mp3=b.canPlayType("audio/mpeg;").replace(/^no$/,""),a.wav=b.canPlayType('audio/wav; codecs="1"').replace(/^no$/,
""),a.m4a=(b.canPlayType("audio/x-m4a;")||b.canPlayType("audio/aac;")).replace(/^no$/,"")}catch(h){}return a};d.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(b){return!1}};d.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(b){return!1}};d.webworkers=function(){return!!e.Worker};d.applicationcache=function(){return!!e.applicationCache};
d.svg=function(){return!!c.createElementNS&&!!c.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};d.inlinesvg=function(){var b=c.createElement("div");return b.innerHTML="<svg/>",(b.firstChild&&b.firstChild.namespaceURI)=="http://www.w3.org/2000/svg"};d.smil=function(){return!!c.createElementNS&&/SVGAnimate/.test(w.call(c.createElementNS("http://www.w3.org/2000/svg","animate")))};d.svgclippaths=function(){return!!c.createElementNS&&/SVGClipPath/.test(w.call(c.createElementNS("http://www.w3.org/2000/svg",
"clipPath")))};for(var F in d)q(d,F)&&(C=F.toLowerCase(),f[C]=d[F](),A.push((f[C]?"":"no-")+C));f.input||z();f.addTest=function(b,a){if(typeof b=="object")for(var h in b)q(b,h)&&f.addTest(h,b[h]);else{b=b.toLowerCase();if(f[b]!==l)return f;a=typeof a=="function"?a():a;t.className+=" "+(a?"":"no-")+b;f[b]=a}return f};m.cssText="";return d=g=null,f._version="2.5.3",f._prefixes=u,f._domPrefixes=j,f._cssomPrefixes=v,f.mq=function(b){var a=e.matchMedia||e.msMatchMedia;if(a)return a(b).matches;var h;return D("@media "+
b+" { #modernizr { position: absolute; } }",function(a){h=(e.getComputedStyle?getComputedStyle(a,null):a.currentStyle).position=="absolute"}),h},f.hasEvent=E,f.testProp=function(b){return x([b])},f.testAllProps=k,f.testStyles=D,f.prefixed=function(b,a,h){return a?k(b,a,h):k(b,"pfx")},t.className=t.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+A.join(" ")),f}(this,this.document);
(function(e,c){function l(d,c){var e=d.createElement("p"),f=d.getElementsByTagName("head")[0]||d.documentElement;return e.innerHTML="x<style>"+c+"</style>",f.insertBefore(e.lastChild,f.firstChild)}function o(){var d=r.elements;return typeof d=="string"?d.split(" "):d}function x(c){var e={},f=c.createElement,g=c.createDocumentFragment,k=g();c.createElement=function(c){var j=(e[c]||(e[c]=f(c))).cloneNode();return r.shivMethods&&j.canHaveChildren&&!d.test(c)?k.appendChild(j):j};c.createDocumentFragment=
Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+o().join().replace(/\w+/g,function(c){return e[c]=f(c),k.createElement(c),'c("'+c+'")'})+");return n}")(r,k)}function k(c){var d;return c.documentShived?c:(r.shivCSS&&!m&&(d=!!l(c,"article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}")),
g||(d=!x(c)),d&&(c.documentShived=d),c)}function z(c){for(var d,e=c.attributes,f=e.length,g=c.ownerDocument.createElement(u+":"+c.nodeName);f--;)d=e[f],d.specified&&g.setAttribute(d.nodeName,d.nodeValue);return g.style.cssText=c.style.cssText,g}function f(c){var d,e,f=c.namespaces,g=c.parentWindow;return!v||c.printShived?c:(typeof f[u]=="undefined"&&f.add(u),g.attachEvent("onbeforeprint",function(){var f,g,k;g=c.styleSheets;for(var p=[],q=g.length,m=Array(q);q--;)m[q]=g[q];for(;k=m.pop();)if(!k.disabled&&
w.test(k.media)){for(f=k.imports,q=0,g=f.length;q<g;q++)m.push(f[q]);try{p.push(k.cssText)}catch(b){}}var a,p=p.reverse().join("").split("{");f=p.length;q=RegExp("(^|[\\s,>+~])("+o().join("|")+")(?=[[\\s,>+~#.:]|$)","gi");for(m="$1"+u+"\\:$2";f--;)a=p[f]=p[f].split("}"),a[a.length-1]=a[a.length-1].replace(q,m),p[f]=a.join("}");var p=p.join("{"),h;a=c.getElementsByTagName("*");f=a.length;q=RegExp("^(?:"+o().join("|")+")$","i");for(m=[];f--;)h=a[f],q.test(h.nodeName)&&m.push(h.applyElement(z(h)));e=
m;d=l(c,p)}),g.attachEvent("onafterprint",function(){for(var c=e,f=c.length;f--;)c[f].removeNode();d.removeNode(!0)}),c.printShived=!0,c)}var t=e.html5||{},d=/^<|^(?:button|form|map|select|textarea)$/i,m,g;(function(){var d=c.createElement("a");d.innerHTML="<xyz></xyz>";m="hidden"in d;g=d.childNodes.length==1||function(){try{c.createElement("a")}catch(d){return!0}var e=c.createDocumentFragment();return typeof e.cloneNode=="undefined"||typeof e.createDocumentFragment=="undefined"||typeof e.createElement==
"undefined"}()})();var r={elements:t.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:t.shivCSS!==!1,shivMethods:t.shivMethods!==!1,type:"default",shivDocument:k};e.html5=r;k(c);var w=/^$|\b(?:all|print)\b/,u="html5shiv",v=!g&&function(){var d=c.documentElement;return typeof c.namespaces!="undefined"&&typeof c.parentWindow!="undefined"&&typeof d.applyElement!="undefined"&&
typeof d.removeNode!="undefined"&&typeof e.attachEvent!="undefined"}();r.type+=" print";r.shivPrint=f;f(c)})(this,document);
(function(e,c,l){function o(a){return u.call(a)=="[object Function]"}function x(a){return typeof a=="string"}function k(){}function z(a){return!a||a=="loaded"||a=="complete"||a=="uninitialized"}function f(){var a=v.shift();j=1;a?a.t?r(function(){(a.t=="c"?b.injectCss:b.injectJs)(a.s,0,a.a,a.x,a.e,1)},0):(a(),f()):j=0}function t(a,d,e,g,k,m,i){function s(c){if(!o&&z(n.readyState)&&(q.r=o=1,!j&&f(),n.onload=n.onreadystatechange=null,c)){a!="img"&&r(function(){A.removeChild(n)},50);for(var b in p[d])p[d].hasOwnProperty(b)&&
p[d][b].onload()}}var i=i||b.errorTimeout,n={},o=0,l=0,q={t:e,s:d,e:k,a:m,x:i};p[d]===1&&(l=1,p[d]=[],n=c.createElement(a));a=="object"?n.data=d:(n.src=d,n.type=a);n.width=n.height="0";n.onerror=n.onload=n.onreadystatechange=function(){s.call(this,l)};v.splice(g,0,q);a!="img"&&(l||p[d]===2?(A.insertBefore(n,y?null:w),r(s,i)):p[d].push(n))}function d(a,c,d,b,e){return j=0,c=c||"j",x(a)?t(c=="c"?C:B,a,c,this.i++,d,b,e):(v.splice(this.i++,0,a),v.length==1&&f()),this}function m(){var a=b;return a.loader=
{load:d,i:0},a}var g=c.documentElement,r=e.setTimeout,w=c.getElementsByTagName("script")[0],u={}.toString,v=[],j=0,G="MozAppearance"in g.style,y=G&&!!c.createRange().compareNode,A=y?g:w.parentNode,g=e.opera&&u.call(e.opera)=="[object Opera]",g=!!c.attachEvent&&!g,B=G?"object":g?"script":"img",C=g?"script":B,D=Array.isArray||function(a){return u.call(a)=="[object Array]"},E=[],p={},q={timeout:function(a,c){return c.length&&(a.timeout=c[0]),a}},F,b;b=function(a){function c(a){var a=a.split("!"),d=E.length,
b=a.pop(),e=a.length,b={url:b,origUrl:b,prefixes:a},h,f,g;for(f=0;f<e;f++)g=a[f].split("="),(h=q[g.shift()])&&(b=h(b,g));for(f=0;f<d;f++)b=E[f](b);return b}function d(a,b,e,g,k){var i=c(a),j=i.autoCallback;i.url.split(".").pop().split("?").shift();i.bypass||(b&&(b=o(b)?b:b[a]||b[g]||b[a.split("/").pop().split("?")[0]]||f),i.instead?i.instead(a,b,e,g,k):(p[i.url]?i.noexec=!0:p[i.url]=1,e.load(i.url,i.forceCSS||!i.forceJS&&"css"==i.url.split(".").pop().split("?").shift()?"c":l,i.noexec,i.attrs,i.timeout),
(o(b)||o(j))&&e.load(function(){m();b&&b(i.origUrl,k,g);j&&j(i.origUrl,k,g);p[i.url]=2})))}function e(a,b){function c(a,e){if(a)if(x(a))e||(g=function(){var a=[].slice.call(arguments);i.apply(this,a);j()}),d(a,g,b,0,f);else{if(Object(a)===a)for(l in m=function(){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}(),a)a.hasOwnProperty(l)&&(!e&&!--m&&(o(g)?g=function(){var a=[].slice.call(arguments);i.apply(this,a);j()}:g[l]=function(a){return function(){var b=[].slice.call(arguments);a&&a.apply(this,
b);j()}}(i[l])),d(a[l],g,b,l,f))}else!e&&j()}var f=!!a.test,h=a.load||a.both,g=a.callback||k,i=g,j=a.complete||k,m,l;c(f?a.yep:a.nope,!!h);h&&c(h)}var g,j,i=this.yepnope.loader;if(x(a))d(a,0,i,0);else if(D(a))for(g=0;g<a.length;g++)j=a[g],x(j)?d(j,0,i,0):D(j)?b(j):Object(j)===j&&e(j,i);else Object(a)===a&&e(a,i)};b.addPrefix=function(a,b){q[a]=b};b.addFilter=function(a){E.push(a)};b.errorTimeout=1E4;c.readyState==null&&c.addEventListener&&(c.readyState="loading",c.addEventListener("DOMContentLoaded",
F=function(){c.removeEventListener("DOMContentLoaded",F,0);c.readyState="complete"},0));e.yepnope=m();e.yepnope.executeStack=f;e.yepnope.injectJs=function(a,d,e,g,j,m){var i=c.createElement("script"),l,n,g=g||b.errorTimeout;i.src=a;for(n in e)i.setAttribute(n,e[n]);d=m?f:d||k;i.onreadystatechange=i.onload=function(){!l&&z(i.readyState)&&(l=1,d(),i.onload=i.onreadystatechange=null)};r(function(){l||(l=1,d(1))},g);j?i.onload():w.parentNode.insertBefore(i,w)};e.yepnope.injectCss=function(a,b,d,e,g,j){var e=
c.createElement("link"),i,b=j?f:b||k;e.href=a;e.rel="stylesheet";e.type="text/css";for(i in d)e.setAttribute(i,d[i]);g||(w.parentNode.insertBefore(e,w),r(b,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};Modernizr.addTest("adownload","download"in document.createElement("a"));
(function(){if(!Modernizr.canvas)return!1;var e=new Image,c=document.createElement("canvas"),l=c.getContext("2d");e.onload=function(){l.drawImage(e,0,0);Modernizr.addTest("todataurljpeg",function(){return c.toDataURL("image/jpeg").indexOf("data:image/jpeg")===0});Modernizr.addTest("todataurlwebp",function(){return c.toDataURL("image/webp").indexOf("data:image/webp")===0})};e.src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg=="})();
Modernizr.addTest("contenteditable","isContentEditable"in document.documentElement);Modernizr.addTest("boxsizing",function(){return Modernizr.testAllProps("boxSizing")&&(document.documentMode===void 0||document.documentMode>7)});Modernizr.addTest("contextmenu","contextMenu"in document.body&&"HTMLMenuItemElement"in window);Modernizr.addTest("mediaqueries",Modernizr.mq("only all"));
Modernizr.addTest("pointerevents",function(){var e=document.createElement("x"),c=document.documentElement,l=window.getComputedStyle,o;return"pointerEvents"in e.style?(e.style.pointerEvents="auto",e.style.pointerEvents="x",c.appendChild(e),o=l&&l(e,"").pointerEvents==="auto",c.removeChild(e),!!o):!1});Modernizr.addTest("json",!!window.JSON&&!!JSON.parse);Modernizr.addTest("notification",!!Modernizr.prefixed("Notifications",window));
Modernizr.addTest("performance",!!Modernizr.prefixed("performance",window));Modernizr.addTest("raf",!!Modernizr.prefixed("requestAnimationFrame",window));Modernizr.addTest("scriptasync","async"in document.createElement("script"));Modernizr.addTest("scriptdefer","defer"in document.createElement("script"));
(function(){try{var e=window.MozURL||window.webkitURL||window.MSURL||window.OURL||window.URL,c=new (window.MozBlobBuilder||window.WebKitBlobBuilder||window.MSBlobBuilder||window.OBlobBuilder||window.BlobBuilder);c.append("this.onmessage=function(e){postMessage(e.data)}");var l=e.createObjectURL(c.getBlob());worker=new Worker(l);c=null;worker.onmessage=function(c){worker.terminate();e.revokeObjectURL(l);Modernizr.addTest("blobworkers","Modernizr"===c.data);worker=null};worker.onerror=function(){Modernizr.addTest("blobworkers",
!1);worker=null};setTimeout(function(){Modernizr.addTest("blobworkers",!1)},200);worker.postMessage("Modernizr")}catch(o){Modernizr.addTest("blobworkers",!1)}})();
(function(){try{var e=new Worker("data:text/javascript;base64,dGhpcy5vbm1lc3NhZ2U9ZnVuY3Rpb24oZSl7cG9zdE1lc3NhZ2UoZS5kYXRhKX0=");e.onmessage=function(c){e.terminate();Modernizr.addTest("dataworkers","Modernizr"===c.data);e=null};e.onerror=function(){Modernizr.addTest("dataworkers",!1);e=null};setTimeout(function(){Modernizr.addTest("dataworkers",!1)},200);e.postMessage("Modernizr")}catch(c){Modernizr.addTest("dataworkers",!1)}})();Modernizr.addTest("sharedworkers",function(){return!!window.SharedWorker});
